### ISSUE TITLE
ReferenceError: REQUEST_APPS is not defined

### ISSUE THREAD

**Issue by Abdubek** [Rohitkrops/ssr#3]
ssr/views/redux/reducer.js
here, too, you need to add import REQUEST_APPS, RECEIVE_APPS

**Comment by RibbtDev** [comment]
Hey, @Abdubek why are you watching inside babel compiled files.  Have a look inside src/redux/reducers.js 

The very first line here is "import { REQUEST_APPS,  RECEIVE_APPS } from './actions';" 
Also, Everything is working fine. If you still have an issue reply soon otherwise I will close this issue.
